//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFPractica1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int ID { get; set; }
        public string Product { get; set; }
        public Nullable<int> price { get; set; }
        public string date_of_purchase { get; set; }
        public int Customers_ID { get; set; }
    
        public virtual Customers Customers {private get; set; }
    }
}
